# Examples using Torch

In [1]:
import torch

### Create a tensor of 6 elements using a random number between -100 and 100

In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([-42,   8, -43,  -3, -94, -43])

### Creating a tensor using torch

In [4]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

### Zeros in Torch

In [5]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### Ones in Torch

In [6]:
ones = torch.ones(2, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

### Create a tensor in a given range

In [7]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

### Create equal dividends using torch, from 3 to 10 with 5 steps

In [8]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

### Increment or Decrement powers of 10, according to given power reduction

In [9]:
logspace = torch.logspace(-10, 10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

### Create diagonal matrix using eye function

In [10]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

# GPU VS CPU

## Switch to GPU processing

In [11]:
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda
